export const TILE_SIZE = 16;

export const BIOME_DECORATIONS = {
  grassland: [
    {
      name: "tree_green",
      sx: 0,
      sy: 48,
      sw: 32,
      sh: 48,
      offsetY: -48,
      frequency: 0.3,
    },
    {
      name: "bush_small",
      sx: 32,
      sy: 48,
      sw: 16,
      sh: 16,
      offsetY: -16,
      frequency: 0.5,
    },
    {
      name: "flower_tuft",
      sx: 32,
      sy: 96,
      sw: 16,
      sh: 16,
      offsetY: -16,
      frequency: 0.6,
    },
    {
      name: "mushroom_red",
      sx: 96,
      sy: 96,
      sw: 16,
      sh: 16,
      offsetY: -16,
      frequency: 0.2,
    },
    {
      name: "crate",
      sx: 96,
      sy: 48,
      sw: 16,
      sh: 16,
      offsetY: -16,
      frequency: 0.15,
    },
    {
      name: "fence",
      sx: 128,
      sy: 48,
      sw: 16,
      sh: 16,
      offsetY: -16,
      frequency: 0.2,
    },
  ],
  desert: [
    {
      name: "palm_tree",
      sx: 32,
      sy: 96,
      sw: 32,
      sh: 64,
      offsetY: -64,
      frequency: 0.25,
    },
    {
      name: "dry_shrub",
      sx: 48,
      sy: 64,
      sw: 16,
      sh: 16,
      offsetY: -16,
      frequency: 0.4,
    },
    {
      name: "bottle_yellow",
      sx: 16,
      sy: 128,
      sw: 16,
      sh: 16,
      offsetY: -16,
      frequency: 0.1,
    },
    {
      name: "signpost",
      sx: 112,
      sy: 48,
      sw: 16,
      sh: 16,
      offsetY: -16,
      frequency: 0.15,
    },
  ],
  snow: [
    {
      name: "tree_pine",
      sx: 80,
      sy: 48,
      sw: 16,
      sh: 48,
      offsetY: -48,
      frequency: 0.35,
    },
    {
      name: "mushroom_blue",
      sx: 112,
      sy: 112,
      sw: 16,
      sh: 16,
      offsetY: -16,
      frequency: 0.25,
    },
    {
      name: "shrub_snowy",
      sx: 64,
      sy: 64,
      sw: 16,
      sh: 16,
      offsetY: -16,
      frequency: 0.4,
    },
  ],
  volcanic: [
    {
      name: "mushroom_purple",
      sx: 112,
      sy: 128,
      sw: 16,
      sh: 16,
      offsetY: -16,
      frequency: 0.3,
    },
    {
      name: "dark_crate",
      sx: 96,
      sy: 64,
      sw: 16,
      sh: 16,
      offsetY: -16,
      frequency: 0.2,
    },
    {
      name: "bottle_red",
      sx: 32,
      sy: 128,
      sw: 16,
      sh: 16,
      offsetY: -16,
      frequency: 0.1,
    },
  ],
  autumn: [
    {
      name: "tree_orange",
      sx: 64,
      sy: 48,
      sw: 16,
      sh: 48,
      offsetY: -48,
      frequency: 0.3,
    },
    {
      name: "pumpkin",
      sx: 64,
      sy: 128,
      sw: 16,
      sh: 16,
      offsetY: -16,
      frequency: 0.2,
    },
    {
      name: "mushroom_orange",
      sx: 96,
      sy: 112,
      sw: 16,
      sh: 16,
      offsetY: -16,
      frequency: 0.3,
    },
  ],
};
